
spring:
  config:
    location: classpath:application*.yml
front-base-url: http://localhost:3000
api-base-url: http://localhost:9000

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/football?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

---

server:
  port : 9000

mybatis:
  mapper-locations:
  - classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true 