server:
  port : 9000
spring:  
  aop:
    auto: true
    proxy-target-class: true
  main:
    allow-circular-references: true    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/football?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root    
    hikari:
      connection-timeout: 300000    
      maximum-pool-size: 5    
  session:  
    timeout: 2592000 #30일
    store-type: redis    
  data:
    redis:
      host: localhost
      port: 6379  
      database: 0
      password: root

mybatis:
  mapper-locations:
  - classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true 
    
logging:
  level:
    jdbc:
      sqlonly: OFF
      sqltiming: INFO
      audit: OFF
      resultset: OFF
      resultsettable: OFF
      connection: OFF    
